name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: uv sync --all-extras
        
    - name: Lint with ruff
      run: |
        uv run ruff check
        uv run ruff format --check
        
    - name: Run tests
      run: |
        uv run pytest tests/ -v --tb=short --cov=starlighter --cov-report=term-missing --cov-report=xml
        
    - name: Test examples
      run: |
        echo "Checking examples for syntax errors..."
        uv run python -m py_compile examples/*.py
        
    - name: Run performance benchmarks
      run: |
        echo "Running performance regression checks..."
        uv run python -m dev_tools.benchmark.runner --check-regression --warmup 3 --samples 50
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.12'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  quality-check:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: All quality checks passed
        run: echo "✅ All quality checks passed!"